config/routes.rb
ActionController::Routing::Routes.draw do |map|
  

  map.departments '/people/departments', :controller => "people", :action => "departments"
  map.schools     '/people/schools',     :controller => "people", :action => "schools"

  map.resources :activity_types
  map.resources :awards, :except => [ :destroy ],
    :member => { :versions => :get, :revert => :post, :details => :get },
    :collection => { :incomplete => :get, :update_ctsa_reporting_year => :post, :search => :get }
  map.resources :ctsa_reports, :except => [ :show ],
    :member => { :download => :get, :irb_iacuc_report => :get, :technology_transfer_report => :get }
  map.resources :publications, :only => [ :edit, :update, :new, :create ],
    :member => { :versions => :get, :revert => :post },
    :collection => { :incomplete => :get, :update_ctsa_reporting_year => :post, :search => :get }
  map.resources :approvals, :only => [ :index ],
    :collection => { :update_approvals => :post, :search => :get }
  map.resources :organizational_units
  
  map.resources :services, 
    :member     => { :choose_service_line => :get, :choose_person => :get, :update_person => :put, :update_approvals => :put, 
                     :continue => [:get, :put], :identified => [:get, :put], :surveyable => :get, :survey => :post,
                     :create_service_for_person => :post,
                     :choose_awards => :get, :choose_organizational_units => :get, :choose_publications => :get, :choose_approvals => :get }, 
    :collection => { :choose_service_line => :get, :choose_person => :get, :my_services => :get }
  
  map.resources :people, :only => [:index, :edit, :update, :new, :create], 
    :member     => { :versions => :get, :revert => :post, :version => :get, :merge => [:get, :post] },
    :collection => { :upload => [:get, :post], :search => [:get,:post], :search_results => [:get,:post], 
                     :directory => [:get, :post], :incomplete => :get, :update_ctsa_reporting_year => :post,
                     :era_commons_username_search => [:get, :post] } do |people|
      people.resources :awards
      people.resources :publications
      people.resources :approvals
      people.resources :services
  end
  map.resources :clients, :controller => "people"
  map.resources :contacts, :collection => { :upload => [:get, :post], :email_search => [:get], :load_contact => [:get], :sample_upload_file => :get }
  map.resources :contact_lists
  
  map.resources :participating_organizations
  map.resources :service_lines
  map.resources :specialties, :only => [ :index ]

  map.resources :users, :except => [ :destroy, :show ]

  map.connect 'reports/:action', :controller => "reports"

  

  map.root :controller => "welcome"

  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
end

app/models/person.rb
# == Schema Information
# Schema version: 20101216175350
#
# Table name: people
#
#  id                                            :integer         not null, primary key
#  type                                          :string(255)
#  first_name                                    :string(255)
#  middle_name                                   :string(255)
#  last_name                                     :string(255)
#  netid                                         :string(255)
#  email                                         :string(255)
#  department_affiliation                        :string(255)
#  school_affiliation                            :string(255)
#  last_four_of_ssn                              :string(255)
#  phone                                         :string(255)
#  era_commons_username                          :string(255)
#  employeeid                                    :string(255)
#  department_id                                 :integer
#  personnelid                                   :string(255)
#  address                                       :string(255)
#  city                                          :string(255)
#  state                                         :string(255)
#  edited_by_user                                :boolean
#  organizational_unit_id                        :integer
#  degree_type_one_id                            :integer
#  degree_type_two_id                            :integer
#  specialty_id                                  :integer
#  country_id                                    :integer
#  ethnic_type_id                                :integer
#  race_type_id                                  :integer
#  disadvantaged_background                      :boolean
#  created_at                                    :datetime
#  updated_at                                    :datetime
#  human_subject_protection_training_institution :string(255)
#  human_subject_protection_training_date        :date
#  service_rendered                              :boolean
#  training_type                                 :string(255)
#  trainee_status                                :string(255)
#  has_disability                                :boolean
#  gender                                        :string(255)
#  title                                         :string(255)
#  fax                                           :string(255)
#  edited                                        :boolean
#  imported                                      :boolean
#  ctsa_reporting_years_mask                     :integer
#  system_administrator                          :boolean
#  created_by                                    :string(255)
#  updated_by                                    :string(255)
#  mentor_era_commons_username                   :string(255)
#  appointment_date                              :date
#  end_date                                      :date
#

# TurboCATS                 ClearCATS
# commons_username          era_commons_username
# middle_initial            middle_name
# area_of_expertise_code    specialty.name
# degree_1                  degree_type_one.name
# degree_2                  degree_type_two.name
# ethnic_category           ethnic_type.name
# racial_category           race_type.name

# Same
# first_name
# last_name
# disadvantaged_background


# ClearCATS only
#  netid                                         :string(255)
#  email                                         :string(255)
#  department_affiliation                        :string(255)
#  school_affiliation                            :string(255)
#  last_four_of_ssn                              :string(255)
#  phone                                         :string(255)
#  human_subject_protection_training_institution :string(255)
#  human_subject_protection_training_date        :date

# TurboCATS only

#  gender                   :string(255)
#  mentor_commons_username  :string(255)
#  invalid                  :boolean
#  validation_messages      :text
#  reporting_year           :string(255)
#  training_type            :string(255)
#  appointed                :boolean
#  accepted                 :boolean
#  applied                  :boolean
#  interviewed              :boolean
#  end_date                 :date
#  date_of_appointment      :date
#  has_disability           :boolean


require 'comma'
require 'bcsec'
class Person < ActiveRecord::Base
  include VersionExportable
  include CtsaReportable
  
  has_paper_trail :ignore => [:ctsa_reporting_years_mask]
  
  SCHOLAR      = "scholar"
  OTHER_CAREER = "other_career_development"
  TRAINEE      = "trainee"
  APPLICANT    = "applicant"
  APPOINTED    = "appointed"
  MALE         = "Male"
  FEMALE       = "Female"
  NOT_REPORTED = "Not_Reported"
  
  TRAINING_TYPES   = [TRAINEE, SCHOLAR, OTHER_CAREER]
  TRAINEE_STATUSES = [APPLICANT, APPOINTED]
  GENDERS          = [NOT_REPORTED, MALE, FEMALE]
  
  belongs_to :department

  has_many :services
  has_many :awards
  has_many :publications
  has_many :approvals
  has_and_belongs_to_many :institution_positions
  has_and_belongs_to_many :organizational_units
    
  belongs_to :country
  belongs_to :degree_type_one
  belongs_to :degree_type_two
  belongs_to :specialty
  belongs_to :ethnic_type
  belongs_to :race_type

  validates_length_of :last_four_of_ssn, :is => 4, :if => proc { |obj| !obj.last_four_of_ssn.blank? }
  
  validates_inclusion_of :training_type,  :in => TRAINING_TYPES,   :if => proc { |obj| !obj.training_type.blank? }
  validates_inclusion_of :trainee_status, :in => TRAINEE_STATUSES, :if => proc { |obj| !obj.trainee_status.blank? }
  validates_inclusion_of :gender,         :in => GENDERS,          :if => proc { |obj| !obj.gender.blank? }
  
  # Person record must have either netid or era_commons_username
  validates_presence_of :netid,                :if => proc { |obj| obj.era_commons_username.blank? and !obj.imported? }
  validates_presence_of :era_commons_username, :if => proc { |obj| obj.netid.blank? and !obj.imported? }
  
  validates_uniqueness_of :netid, :if => proc { |obj| !obj.netid.blank? }
  # validates_uniqueness_of :era_commons_username, :if => proc { |obj| !obj.era_commons_username.blank? }
  
  validates_presence_of :last_name,  :if => proc { |obj| !obj.imported? }
  validates_presence_of :first_name, :if => proc { |obj| !obj.imported? }
  # validates_presence_of :email,      :if => proc { |obj| !obj.imported? }
  
  accepts_nested_attributes_for :awards,       :allow_destroy => true
  accepts_nested_attributes_for :publications, :allow_destroy => true
  accepts_nested_attributes_for :approvals,    :allow_destroy => true
  
  named_scope :awards_phs_organization_id_equals,     lambda { |id|  {:joins => :awards, :conditions => ["awards.organization_id  = :id and awards.organization_type = 'PhsOrganization'",    {:id => id} ]} }
  named_scope :awards_activity_code_id_equals,        lambda { |id|  {:joins => :awards, :conditions => ["awards.activity_code_id = :id",       {:id => id} ]} }
  named_scope :awards_non_phs_organization_id_equals, lambda { |id|  {:joins => :awards, :conditions => ["awards.organization_id  = :id and awards.organization_type = 'NonPhsOrganization'", {:id => id} ]} }
  
  named_scope :organizational_units_organizational_unit_id_equals, lambda { |id| {:joins => :organizational_units, :conditions => ["organizational_units.id = :id", {:id => id} ]} }
  
  named_scope :all_investigators, :conditions => "((training_type IS NULL) AND (trainee_status IS NULL))"
  named_scope :all_trainees,      :conditions => "((training_type IS NOT NULL OR training_type = '') AND (trainee_status IS NOT NULL OR trainee_status = ''))"
  
  named_scope :for_reporting_year, lambda { |yr| {:conditions => "people.ctsa_reporting_years_mask & #{2**Person::REPORTING_YEARS.index(yr.to_i)} > 0"} }
  
  named_scope :scholars,      :conditions => { :training_type => SCHOLAR, :trainee_status => APPOINTED }
  named_scope :other_careers, :conditions => { :training_type => OTHER_CAREER, :trainee_status => APPOINTED }
  named_scope :trainees,      :conditions => { :training_type => TRAINEE, :trainee_status => APPOINTED }
  
  named_scope :invalid_for_ctsa_reporting, :conditions => "(people.ctsa_reporting_years_mask & #{2**REPORTING_YEARS.index(SYSTEM_CONFIG['current_ctsa_reporting_year'].to_i)} > 0) AND (era_commons_username IS NULL OR specialty_id IS NULL)"
  
  # attributes from faculty_web_service that are not persisted
  attr_accessor :interests, :campus, :descriptions, :dv_abbr
  attr_accessor :basis, :category, :dept_id, :career_track, :degree, :division
  attr_accessor :joint, :rank, :employee_id, :division_id, :pmids, :centers, :secondary
  attr_accessor :demographics, :certifications, :field_of_study
  
  def employee_id=(emplid)
    self.employeeid = emplid if !emplid.blank? && emplid.to_i > 0
  end
  
  def to_s
    "#{full_name}"
  end
  
  def ctsa_name
    "#{last_name}, #{first_name} #{middle_initial}".strip
  end
  
  def middle_initial
    middle_name.to_s.length > 0 ? "#{middle_name[0,1]}." : ""
  end
  
  def full_name
    [first_name, middle_name, last_name].reject { |n| n.nil? or n.blank? }.join(' ')
  end
  
  before_save :clean_or_set_attributes
  
  def clean_or_set_attributes
    set_affiliations
    upcase_era_commons_username
  end
  
  def upcase_era_commons_username
    self.era_commons_username = self.era_commons_username.upcase unless self.era_commons_username.blank?
  end
  
  def set_affiliations
    if self.department
      self.department_affiliation = self.department.entity_name unless self.department.entity_name.blank?
      self.school_affiliation     = self.department.school      unless self.department.school.blank?
    end
  end
  
  def awards_for_organization(org)
    results = self.awards.select {|a| a.organization == org}
    results
  end

  def business_phone=(phone_number)
    self.phone = phone_number
  end
  
  def business_phone
    self.phone
  end
  

app/models/publication.rb
# == Schema Information
# Schema version: 20101216175350
#
# Table name: publications
#
#  id                        :integer         not null, primary key
#  pmcid                     :string(255)
#  pmid                      :string(255)
#  nihms_number              :string(255)
#  publication_date          :date
#  person_id                 :integer
#  abstract                  :text
#  title                     :string(1000)
#  nucats_assisted           :boolean
#  edited_by_user            :boolean
#  created_at                :datetime
#  updated_at                :datetime
#  cited                     :boolean
#  missing_pmcid_reason      :string(255)
#  ctsa_reporting_years_mask :integer
#  created_by                :string(255)
#  updated_by                :string(255)
#

# TurboCATS             ClearCATS
# pubmed_id             pmcid

# Same
#  person_id
#  cited
#  missing_pmcid_reason
#  reporting_year

# TurboCATS only
#  manuscript_id        :integer
#  invalid              :boolean
#  validation_messages  :text

require 'comma'
class Publication < ActiveRecord::Base
  include VersionExportable
  include CtsaReportable
  
  has_paper_trail :ignore => [:ctsa_reporting_years_mask]
  
  belongs_to :person
  
  named_scope :nucats_assisted_eq, lambda { |flag| {:conditions => "publications.nucats_assisted IS TRUE"} if flag == "1" || flag.to_i == 1 || flag == true}
  named_scope :all_for_reporting_year, lambda { |yr| {:conditions => "publications.ctsa_reporting_years_mask & #{2**REPORTING_YEARS.index(yr.to_i)} > 0 "} }
  named_scope :invalid_for_ctsa, :conditions => "(publications.ctsa_reporting_years_mask & #{2**REPORTING_YEARS.index(SYSTEM_CONFIG['current_ctsa_reporting_year'].to_i)} > 0) AND (pmid IS NULL OR pmid = '')"

  # Attributes from LatticeGrid/PubMed
  attr_accessor :endnote_citation, :authors, :full_authors, :is_first_author_investigator, :is_last_author_investigator
  attr_accessor :journal_abbreviation, :volume, :issue, :pages, :year, :publication_type, :electronic_publication_date
  attr_accessor :deposited_date, :status, :publication_status, :issn, :isbn, :citation_last_get_at, :citation_url, :url, :mesh
  attr_accessor :created_id, :created_ip, :created_at, :updated_id, :updated_ip, :updated_at, :deleted_at, :deleted_id, :deleted_ip
  attr_accessor :mesh_vector, :journal_vector, :abstract_vector, :is_cancer, :vectors
  
  def pubmed=(pubmed)
    self.pmid = pubmed
  end
  
  def pubmed
    self.pmid
  end
  
  def pubmedcentral=(pubmedcentral)
    self.pmcid = pubmedcentral
  end
  
  def pubmedcentral
    self.pmcid
  end
  
  def formatted_publication_date
    self.publication_date.strftime("%m/%d/%Y") unless self.publication_date.nil?
  end

  def formatted_publication_date=(dt)
    self.publication_date = dt
  end

  def pubmed_id
    self.pmid.to_s.strip
  end
  
  def previously_reported?(yr)
    return false if ctsa_reporting_years_mask.nil?
    return false if ctsa_reporting_years_mask.to_i == 0
    return false if ctsa_reporting_years.size == 1 and ctsa_reporting_years.include?(yr)
    true
  end
  
  def self.reporting_years(reporting_years_mask)
    REPORTING_YEARS.reject { |yr| ((reporting_years_mask || 0) & 2**REPORTING_YEARS.index(yr)).zero? }  
  end
  
  ###
  #    Support for exporting to CSV
  ###
  
  comma do
    person
    pmcid
    pmid
    nihms_number
    publication_date
    journal
    title
    abstract
    nucats_assisted
    cited
    missing_pmcid_reason
    ctsa_reporting_years :to_sentence => "CTSA Reporting Years"
  end
  
end

app/views/publications/_form.html.haml
- stylesheet "awards"

- if @show_header
  %span{ :class => "publication_header" }
    Publication for #{@publication.person} 
    = link_to "PubMed", "http://www.ncbi.nlm.nih.gov/pubmed?term=#{@publication.pmid}[uid]", :popup => true, :class => "external_link icon_link" unless @publication.pmid.blank?

  .header_option
    = link_to("Close", "javascript: jQuery.unblockUI();", :class => "delete_link icon_link")

  .page_section
    %div{ :id => "publication_form", :class => "publications" }
      - form_remote_for @publication, :html => { :id => "modal_edit_form"} do |f|
        = hidden_field_tag :person_id, @person.id if @person
        = hidden_field_tag :service_id, @service.id if @service
        = f.hidden_field :person_id
        = hidden_field_tag "publication[edited_by_user]", true
        - if params[:search]
          - params[:search].each do |k, v| 
            = hidden_field_tag "search[#{k}]", v

        = render 'publication_fields', {:f => f}

- else
  .page_section
    %div{ :id => "publication_form", :class => "publications" }
      - form_for @publication, :html => { :id => "edit_form"} do |f|
        = hidden_field_tag :service_id, @service.id if @service
        = f.hidden_field :person_id
        = hidden_field_tag "publication[edited_by_user]", true
        - if params[:search]
          - params[:search].each do |k, v| 
            = hidden_field_tag "search[#{k}]", v

        = render 'publication_fields', {:f => f}

    .links
      = link_to 'View Other Publications', person_publications_path(@publication.person), :class => "list_link icon_link menu_nav"
      = link_to 'Back', :back, :class => "back_link icon_link menu_nav"

app/views/publications/_invalid_for_ctsa_tooltip.html.haml
.tooltip
  %h4
    Invalid Publications
  %p
    Publications are ineligible for CTSA Reporting if they are missing the PMID.

app/views/publications/_list.html.haml
#publications
  - if person.netid.blank?
    .notice
      Publications are culled from Lattice Grid by the netid. #{person} is missing a netid.
      = link_to "Update #{person}.", edit_person_path(person), :class => "edit_link icon_link"

  - if service
    - ordering_params = { :controller => "services", :action => "choose_publications", :id => service.id, :view_all => params[:view_all] }
    - pub_association = { :service_id => service.id }
  - else 
    - ordering_params = { :controller => "publications", :action => "index", :person_id => person.id, :view_all => params[:view_all] }
    - pub_association = { :person_id => person.id }

  .publications_body
    .records_header
      = link_to "Add New Publication", { :controller => "/publications", :action => "new", :search => @search_params, :person_id => person.id }.merge(pub_association), { :class => "edit_modal_form_link add_link icon_link", :onclick => "return edit_modal_form(this)" }
      - if service.nil? and !faculty_member?
        - if params[:view_all].blank?
          = link_to 'View All Publications', person_publications_path(person, :view_all => true), :class => "list_link icon_link" 
        - else
          = link_to "View Publications since #{SYSTEM_CONFIG['ctsa_base_line_year']}", person_publications_path(person), :class => "list_link icon_link" 

    - if publications
      = render 'publications/publications_table', { :ordering_params => ordering_params, :pub_association => pub_association }
        

app/views/publications/_publication_fields.html.haml
.span-18
  .span-9
    %p
      = f.label :ctsa_reporting_years, "CTSA Reporting Years"
      %br
      =h null_safe(f.object.ctsa_reporting_years.last)
      
    - unless faculty_member?
      %p
        = f.check_box "nucats_assisted"
        = f.label :nucats_assisted, "#{SYSTEM_CONFIG['grant_name']} Assisted"
    %p
      = f.check_box "ctsa_reportable"
      = f.label :ctsa_reportable, "#{ctsa_wording}"
    %p
      = f.label :pmid, "PMID"
      %br
      = f.text_field :pmid
      %br
      = link_to "PMCID to PMID Converter", "http://www.ncbi.nlm.nih.gov/sites/pmctopmid", :popup => true, :class => "external_link icon_link"
    %p
      = f.label :pmcid, "PMCID"
      %br
      = f.text_field :pmcid
    %p
      = f.label :nihms_number, "NIHMS Number"
      %br
      = f.text_field :nihms_number
    %p
      = f.label :missing_pmcid_reason, "Missing PMCID Reason"
      %br
      = f.text_field :missing_pmcid_reason
    %p
      = f.check_box :cited
      = f.label :cited, "Cited #{SYSTEM_CONFIG['grant_name']} (#{SYSTEM_CONFIG['grant_number']})"
    %p
      = f.label :citation_cnt, "Citation Count"
      = f.text_field :citation_cnt, :size => 4
  .span-9.last
    %p
      = f.label :formatted_publication_date, "Publication Date (mm/dd/yyyy)"
      %br
      = f.text_field :formatted_publication_date, :class => "datepicker"
    %p 
      = f.label :journal, "Journal"
      %br
      = f.text_field :journal
    %p 
      = f.label :title, "Title"
      %br
      = f.text_area :title
    %p 
      = f.label :abstract, "Abstract"
      %br
      = f.text_area :abstract

.buttons
  = f.submit "Save", :class => "close"

app/views/publications/_publications_table.html.haml
- user = get_current_user
- sysadmin = user.respond_to?(:sysadmin?) && user.sysadmin?

- if @publications.blank?
  .no-records
    No publications found for #{@person}.
- else
  - form_tag(update_ctsa_reporting_year_publications_path) do
    = hidden_field_tag "person_id", @person.id
    - current_year = current_ctsa_reporting_year
    %table.records
      %tr
        - unless @service
          %th
            = ctsa_wording
        %th Select
        %th Reporting Years
        %th
          = order @search, :by => :pmcid, :as => "PMCID"
        %th
          = order @search, :by => :pmid, :as => "PMID"
        %th
          = order @search, :by => :nihms_number, :as => "NIHMS Number"
        %th
          = order @search, :by => :publication_date, :as => "Publication Date"
        %th
          = order @search, :by => :title, :as => "Title"
        %th 
          = "History" if sysadmin
      - @publications.each do |pub|
        %tr{ :class => cycle('even_record', 'odd_record') }
          - unless @service
            %td
              = check_box_tag "publication_ids[]", pub.id, pub.ctsa_reporting_years.include?(current_year), { :disabled => pub.previously_reported?(current_year) }
          %td
            = link_to "Select", { :controller => "/publications", :action => "edit", :id => pub, :search => params[:search] }.merge(pub_association), { :class => "edit_modal_form_link edit_link icon_link", :onclick => "return edit_modal_form(this)" }
          %td= h pub.ctsa_reporting_years.blank? ? "n/a" : pub.ctsa_reporting_years.join(",")
          %td= h pub.pmcid
          %td= h pub.pmid
          %td= h pub.nihms_number
          %td= h pub.publication_date
          %td= h pub.title
          %td= link_to 'View', versions_publication_path(pub), :class => "show_link icon_link" if sysadmin
    - unless @service
      .buttons
        - lbl = faculty_member? ? "Save and Continue" : "Save"
        = submit_tag lbl

app/views/publications/_search_form.html.haml
#publication_search_form
  - form_for @search, :method => :get do |f|
    .span-24
      .span-5
        = f.label :person_first_name_like, "First Name"
      .span-7
        = f.text_field :person_first_name_like
      .span-6
        = f.label :person_last_name_like, "Last Name"
      .span-6.last
        = f.text_field :person_last_name_like
    .span-24
      .span-5
        = f.label :pmcid_like, "PMCID"
      .span-7
        = f.text_field :pmcid_like
      .span-6
        = f.label :pmid_like, "PMID"
      .span-6.last
        = f.text_field :pmid_like

    .span-24
      .span-5
        = f.label :title_like, "Title"
      .span-7
        = f.text_field :title_like
      .span-6
        = f.label :abstract_like, "Abstract"
      .span-6.last
        = f.text_field :abstract_like

    .span-24
      .span-5
        = f.label :all_for_reporting_year, "CTSA Reporting Year"
      .span-7
        = f.select :all_for_reporting_year, Publication::REPORTING_YEARS.collect{ |yr| [yr.to_i, yr.to_s]}, { :include_blank => "--" }
      .span-6
        = f.label :invalid_for_ctsa, "Invalid for CTSA Reporting"
        %span{ :class => "help_icon" }
          &nbsp;
        = render "/publications/invalid_for_ctsa_tooltip"
      .span-6.last
        = f.check_box :invalid_for_ctsa
    
    .span-24
      .span-5
        &nbsp;
      .span-7
        &nbsp;
      .span-6
        = f.label :nucats_assisted_eq, "NUCATS Assisted"
      .span-6.last
        = f.check_box :nucats_assisted_eq
        
        
    .buttons
      = f.submit "Search", :disable_with => 'Searching...'
      = link_to "New Search", {:controller => "publications", :action => "search"}, {:class => "search_link icon_link"}
      = link_to "Export All Results", { :controller => "publications", :action => "search", :format => "csv", :params => params }, { :class => "export_link icon_link" }

app/views/publications/_search_results.html.haml
- user = get_current_user
- sysadmin = user.respond_to?(:sysadmin?) && user.sysadmin?

- if @publications.blank?
  .no-records
    No publications found.
- else
  .records_header
    .page_entries_info
      = page_entries_info @publications, :entry_name => "record"
    = will_paginate @publications

  %table.records
    %tr
      %th Edit
      %th 
        = order @search, :by => :person_last_name, :as => "Person", :params => { :controller => "publications", :action => "search" }
      %th 
        = order @search, :by => :publication_date, :as => "Publication Date", :params => { :controller => "publications", :action => "search" }
      %th
        = order @search, :by => :title, :as => "Title", :params => { :controller => "publications", :action => "search" }
      %th
        = order @search, :by => :pmid, :as => "PMID", :params => { :controller => "publications", :action => "search" }
      %th
        = order @search, :by => :pmcid, :as => "PMCID", :params => { :controller => "publications", :action => "search" }
      %th
        = order @search, :by => :nihms_number, :as => "NIHMS Number", :params => { :controller => "publications", :action => "search" }
      %th
        = order @search, :by => :cited, :as => "Cited", :params => { :controller => "publications", :action => "search" }
      %th
        Reporting Year
    - @publications.each do |pub|
      %tr{ :class => cycle('even_record', 'odd_record') }
        %td= link_to "Edit", { :controller => "publications", :action => "edit", :id => pub, :search => params[:search], :person_id => pub.person.id }, { :class => "edit_link icon_link" }
        %td= h pub.person
        %td= h pub.publication_date
        %td= h truncate(pub.title, :length => 50)
        %td= h pub.pmid
        %td= h pub.pmcid
        %td= h pub.nihms_number
        %td= h pub.cited? ? "Yes" : "No"
        %td= h pub.ctsa_reporting_years.join(",")

  = will_paginate @publications

app/views/publications/edit.html.haml
- stylesheet "services"
- title "Publication for #{@publication.person}"

:javascript
  $(function () { $(".datepicker").live('mouseover', function() { $(this).datepicker(); }); });
  $(function () { $("input").live('focus', function() { $(this).closest('form').dirty_form(); }); });
  $(function () { $("select").live('focus', function() { $(this).closest('form').dirty_form(); }); });
  $(function () { $("a.delete_link").live('focus', function() { $(this).dirty_stopper(); }); });
  
.publication_form
  = render 'form'

app/views/publications/incomplete.html.haml
- stylesheet "publications", "services"
- title "Incomplete Publications"

.instructions
  The following records are ineligible for CTSA Reporting. They are missing the PMID.

%table.records
  %tr
    %th Edit
    %th 
      = order @search, :by => :person_last_name, :as => "Person", :params => { :controller => "publications", :action => "incomplete" }
    %th 
      = order @search, :by => :publication_date, :as => "Publication Date", :params => { :controller => "publications", :action => "incomplete" }
    %th
      = order @search, :by => :title, :as => "Title", :params => { :controller => "publications", :action => "incomplete" }
    %th
      = order @search, :by => :pmid, :as => "PMID", :params => { :controller => "publications", :action => "incomplete" }
    %th
      = order @search, :by => :nihms_number, :as => "NIHMS Number", :params => { :controller => "publications", :action => "incomplete" }
    %th
      = order @search, :by => :cited, :as => "Cited", :params => { :controller => "publications", :action => "incomplete" }
    %th
      Reporting Year
  - @publications.each do |pub|
    %tr{ :class => cycle('even_record', 'odd_record') }
      %td= link_to "Edit", { :controller => "publications", :action => "edit", :id => pub, :search => params[:search], :person_id => pub.person.id }, { :class => "edit_link icon_link" }
      %td= h pub.person
      %td= h pub.publication_date
      %td= h truncate(pub.title, :length => 50)
      %td= h pub.pmid
      %td= h pub.nihms_number
      %td= h pub.cited? ? "Yes" : "No"
      %td= h pub.ctsa_reporting_years.join(",")

= will_paginate @publications

app/views/publications/new.html.haml
- stylesheet "services"
- title "Publication for #{@publication.person}"

:javascript
  $(function () { $(".datepicker").live('mouseover', function() { $(this).datepicker(); }); });

.publication_form
  = render 'form'